project_id = "rdatyftacldjhgzsxzfw"

[functions.create-user]
verify_jwt = true

[functions.calculate-analytics]
verify_jwt = true

[functions.send-weekly-duty-coverage]
verify_jwt = true

[functions.vacation-recommendations]
verify_jwt = true

[functions.send-swap-notification]
verify_jwt = true

[functions.send-schedule-notification]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.vacation-request-notification]
verify_jwt = true